application: nutri-good
version: 1
runtime: php55
api_version: 1

handlers:
- url: /assets
  static_dir: assets

- url: /bootstrap
  static_dir: bootstrap

- url: /
  script: index.php

- url: /css
  static_dir: css

- url: /js
  static_dir: js
